version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - ./mongo-init/:/docker-entrypoint-initdb.d/
    environment:
      MONGO_INITDB_DATABASE: lms
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password

  lms:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lms
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    env_file:
      - .env.production

volumes:
  mongo_data:
